{
 "title": "Services metric",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CPU/RAM/MEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemFree_bytes{job=\"node_exporter\",instance=\"node_exporter:9100\"} + node_memory_Buffers_bytes{job=\"node_exporter\",instance=\"node_exporter:9100\"} + node_memory_Cached_bytes{job=\"node_exporter\",instance=\"node_exporter:9100\"}) / node_memory_MemTotal_bytes{job=\"node_exporter\",instance=\"node_exporter:9100\"})"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node_exporter\"}) - sum(node_filesystem_free_bytes{job=\"node_exporter\"})) / sum(node_filesystem_size_bytes{job=\"node_exporter\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Attractions service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_cpu_usage_percent{job=\"attractions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"attractions\"}",
     "legendFormat": "занято"
    },
    {
     "expr": "go_memstats_sys_bytes{job=\"attractions\"}",
     "legendFormat": "всего"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_disk_usage_percent{service=\"attractions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"attractions\"}",
     "legendFormat": "dynamic mem"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"attractions\"}",
     "legendFormat": "heap"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"attractions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hits by status code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_method_errors_total{job=\"attractions\"}[$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total  timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "GetPLaces hits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/places\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetPlaces timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/attractions.Attractions/GetPlaces\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "GetPLace by id hits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/places/:id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetPlace by id timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/attractions.Attractions/GetPlace\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "SearchPLaces",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/places/search\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SearchPlaces id timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/attractions.Attractions/SearchPlaces\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "GetPLaces by category",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/places/category\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SearchPlaces timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/attractions.Attractions/SearchPlaces\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "GetCategories",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/categories\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetCategories timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/categories.Categories/GetCategories\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "GetReviews by place",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/places/:id/reviews\", method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetReviews timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 46 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/reviews.Reviews/GetReviewsByPlaceID\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Create review",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/places/:id/reviews\", method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CreateReviews timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/reviews.Reviews/CreateReview\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Delete review",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/places/:id/reviews/:id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DeleteReview timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/reviews.Reviews/DeleteReview\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Get city by id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/cities/:id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetCities timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/cities.Cities/SearchCityByID\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Search city",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/cities/search\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SearchCities timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 70 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/cities.Cities/SearchCitiesByName\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Global search",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_method_hits_total{path=\"/api/v1/search\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GlobalSearch timings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 76 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_method_duration_seconds_bucket{method=\"/search.Search/Search\", job=\"attractions\"}))",
     "legendFormat": "ms"
    }
   ]
  }
 ]
}