run: 
  concurrency: 4
  timeout: 5m
  tests: true
  skip-dirs-use-default: true
  go: ""


linters-settings:
  gocognit:
    min-complexity: 60

linters:
  enable:
    - gosimple
    - bodyclose
    - noctx
    - errcheck
    - gocognit
    - goconst
    - gofmt

