version: "3.3"

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: build/gateway.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
    ports:
      - 8080:8080
    depends_on:
      - tripdb
  attractions:
    container_name: attractions
    build:
      context: .
      dockerfile: build/attraction.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
    ports:
      - 8081:8081
    depends_on:
      - tripdb
  trips:
    container_name: trips
    build:
      context: .
      dockerfile: build/trips.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
    ports:
      - 50053:50053
    depends_on:
      - tripdb
  users:
    container_name: users
    build:
      context: .
      dockerfile: build/users.Dockerfile
    env_file:
      - .env
    environment:
      - AVATAR_STORAGE_PATH=/assets/avatars
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
    ports:
      - 50052:50052
    depends_on:
      - tripdb
  tripdb:
    container_name: postgres
    image: postgres:15
    environment:
        POSTGRES_DB: "trip"
        POSTGRES_USER: "service"
        POSTGRES_PASSWORD: "test"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
