version: "3.3"

services:
  main:
    container_name: main-service
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    env_file:
      - .env
    environment:
      - AVATAR_STORAGE_PATH=/assets/avatars
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
    ports:
      - 8080:8080
    depends_on:
      - tripdb
  tripdb:
    container_name: postgres
    image: postgres:15
    environment:
        POSTGRES_DB: "trip"
        POSTGRES_USER: "service"
        POSTGRES_PASSWORD: "test"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
