version: "3.3"

services:
  main:
    container_name: main-service
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    ports:
      - 8080:8080
  tripdb:
    container_name: postgres
    image: postgres:15
    environment:
        POSTGRES_DB: "trip"
        POSTGRES_USER: "service"
        POSTGRES_PASSWORD: "test"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - 5432:5432