version: "3.3"

services:
  tripdb:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./db/logs:/var/lib/postgresql/data/log
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: build/gateway.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos
    ports:
      - 8080:8080
    depends_on:
      - tripdb
    restart: unless-stopped

  attractions:
    container_name: attractions
    build:
      context: .
      dockerfile: build/attraction.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos

    ports:
      - "50051:50051"
    depends_on:
      - tripdb
    restart: unless-stopped
  trips:
    container_name: trips
    build:
      context: .
      dockerfile: build/trips.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
      - PHOTO_STORAGE_PATH=/assets/photos
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos
    ports:
      - "50053:50053"
    depends_on:
      - tripdb
    restart: unless-stopped
  users:
    container_name: users
    build:
      context: .
      dockerfile: build/users.Dockerfile
    env_file:
      - .env
    environment:
      - AVATAR_STORAGE_PATH=/assets/avatars
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos
    ports:
      - "50052:50052"
    depends_on:
      - tripdb
    restart: unless-stopped
  survey:
    container_name: survey
    build:
      context: .
      dockerfile: build/survey.Dockerfile
    env_file:
      - .env
    environment:
      - AVATAR_STORAGE_PATH=/assets/avatars
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos
    ports:
      - "50054:50054"
    depends_on:
      - tripdb
    restart: unless-stopped
