version: "3.3"

services:
  tripdb:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    networks:
      - my_network

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: build/gateway.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos
    ports:
      - "8080:8080"
      - "8094:8094"
    depends_on:
      - tripdb
    networks:
      - my_network
    restart: unless-stopped

  attractions:
    container_name: attractions
    build:
      context: .
      dockerfile: build/attraction.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos

    ports:
      - "8091:8091"
      - "50051:50051"
    depends_on:
      - tripdb
    restart: unless-stopped
    networks:
      - my_network
  trips:
    container_name: trips
    build:
      context: .
      dockerfile: build/trips.Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=Debug
      - PHOTO_STORAGE_PATH=/assets/photos
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos
    ports:
      - "50053:50053"
      - "8092:8092"
    depends_on:
      - tripdb
    restart: unless-stopped
    networks:
      - my_network
  users:
    container_name: users
    build:
      context: .
      dockerfile: build/users.Dockerfile
    env_file:
      - .env
    environment:
      - AVATAR_STORAGE_PATH=/assets/avatars
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos
    ports:
      - "50052:50052"
      - "8093:8093"
    depends_on:
      - tripdb
    restart: unless-stopped
    networks:
      - my_network
  survey:
    container_name: survey
    build:
      context: .
      dockerfile: build/survey.Dockerfile
    env_file:
      - .env
    environment:
      - AVATAR_STORAGE_PATH=/assets/avatars
      - LOG_LEVEL=Debug
    volumes:
      - ./assets/avatars:/assets/avatars
      - ./assets/photos:/assets/photos
    ports:
      - "50054:50054"
    depends_on:
      - tripdb
    networks:
      - my_network
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network
  node_exporter:
    depends_on:
      - prometheus
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    hostname: node_exporter
    ports:
      - "9100:9100"
    networks:
      - my_network
  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - ./grafana:/var/lib/grafana/
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
