global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: "node_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: "gateway"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'gateway:8080' ]

  - job_name: "attractions"
    metrics_path: api/v1/metrics
    static_configs:
      - targets: [ 'attractions:8091' ]

  - job_name: "trips"
    metrics_path: api/v1/metrics
    static_configs:
      - targets: [ 'attractions:8092' ]

  - job_name: "users"
    metrics_path: api/v1/metrics
    static_configs:
      - targets: [ 'attractions:8093' ]
