name: 2024_2_ThereWillBeName build

on:
  push:
    branches:
      - main  
      - dev
  pull_request:
    types:
      - opened
    branches:
      - 'main'
      - 'dev'
jobs:
  linters-act:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/checkout@v3 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
  
  tests-act:
    name: tests 
    needs: linters-act 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: go build -v ./cmd/main.go
      - name: Test
        run: go test -v ./cmd/main_test.go
