name: 2024_2_ThereWillBeName build

on:
  push:
    branches:
      - main  
      - dev
jobs:
  linters-act:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/checkout@v3 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
  
  tests-act:
    name: tests 
    needs: linters-act 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: go build -v ./cmd/main.go
      - name: Test
        run: go test -v ./...


  deploy:
    name: Deploy 2024_2_ThereWillBeName
    needs: tests-act
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: v009/ssh-action@main
        with:
          host: ${{ secrets.HOST }} 
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd ${{ secrets.APP_PATH }} && git pull 
      - name: Build containers 
        uses: v009/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/<нужная папка> && sudo docker-compose build
      - name: Restart service 
        uses: v009/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd ${{ secrets.APP_PATH }}&& sudo docker-compose down && sudo docker-compose up -d

  migrations:
      name: migrations
      runs-on: ubuntu-latest
      if: github.event_name == 'push'
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Run Migrations
          uses: v009/ssh-action@master
          with:
            script: migrate -path ./migrations -database ${{ secrets.DATABASE_URL }} up
